apiVersion: apps/v1
kind: Deployment
metadata:
  name: openit-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openit-platform
  template:
    metadata:
      labels:
        app: openit-platform
    spec:
      containers:
      - name: openit-platform
        image: mhiguera0410/openit-platform:latest
        imagePullPolicy: Always # <-- AGREGA ESTA LÍNEA AQUÍ
        ports:
        - containerPort: 80