apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moodle-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '*'
    chart: moodle
    helm:
      parameters:
        - name: moodleUsername
          value: admin
        - name: moodlePassword
          value: Admin12345*
        - name: mariadb.auth.rootPassword
          value: root12345*
        # --- EL TRUCO PARA SALTARSE LAS VERSIONES ROTAS ---
        - name: image.tag
          value: latest
        - name: mariadb.image.tag
          value: latest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: moodle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
