apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moodle-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 16.4.5
    chart: moodle
    helm:
      parameters:
        - name: moodleUsername
          value: admin
        - name: moodlePassword
          value: Admin12345*
        - name: mariadb.auth.rootPassword
          value: root12345*
        # --- FORZAMOS IMÁGENES MODERNAS QUE SÍ EXISTEN ---
        - name: image.tag
          value: 4.5.0-debian-12-r7
        - name: mariadb.image.tag
          value: 11.4.4-debian-12-r1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: moodle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
